name: Combined Tests

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes for test_b
    - cron: '*/15 * * * *'  # Run every 10 minutes for test_d
    - cron: '*/30 * * * *'  # Run every 30 minutes for test and test_c
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Select Job to Run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - test_b
          - test
          - test_c
          - test_d
          - test_s

jobs:
  test_b:
    if: github.event.schedule == '*/10 * * * *' || (github.event_name == 'workflow_dispatch' && (inputs.job_to_run == 'all' || inputs.job_to_run == 'test_b'))
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create Files from Secrets
        env:
          B_LIST: ${{ secrets.B_LIST }}
          B_REQ: ${{ secrets.B_REQ }}
          B_TEST: ${{ secrets.B_TEST }}
        run: |
          echo "$B_LIST" > a.txt
          echo "$B_REQ" > req.txt
          echo "$B_TEST" > test.py

      - name: Install Dependencies
        run: |
          if [ -f req.txt ]; then pip install -r req.txt; fi

      - name: Run
        run: |
          python test.py > /dev/null 2>&1

      - name: Commit and Push State
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f data2 ]; then
            git pull
            git add data2
            git commit -m "Update state" || echo "No changes to commit"
            git push
          fi

  test_d:
    if: github.event.schedule == '*/10 * * * *' || (github.event_name == 'workflow_dispatch' && (inputs.job_to_run == 'all' || inputs.job_to_run == 'test_d'))
    runs-on: ubuntu-latest
    permissions:
      contents: write

    services:
      flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
          - "8191:8191"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create Files from Secrets
        env:
          D_REQ: ${{ secrets.D_REQ }}
          D_TEST: ${{ secrets.D_TEST }}
        run: |
          echo "$D_REQ" > req.txt
          echo "$D_TEST" > test.py

      - name: Install Dependencies
        run: |
          if [ -f req.txt ]; then pip install -r req.txt; fi

      - name: Run
        run: |
          python test.py

      - name: Commit and Push State
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f data4 ]; then
            git pull
            git add data4
            git commit -m "Update state data4" || echo "No changes to commit"
            git push
          fi

  test_s:
    if: github.event.schedule == '*/15 * * * *' || (github.event_name == 'workflow_dispatch' && (inputs.job_to_run == 'all' || inputs.job_to_run == 'test_s'))
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create Files from Secrets
        env:
          S_REQ: ${{ secrets.S_REQ }}
          S_TEST: ${{ secrets.S_TEST }}
        run: |
          echo "$S_REQ" > req.txt
          echo "$S_TEST" > test.py

      - name: Install Dependencies
        run: |
          if [ -f req.txt ]; then pip install -r req.txt; fi

      - name: Run
        run: |
          python test.py

  test:
    if: github.event.schedule == '*/30 * * * *' || (github.event_name == 'workflow_dispatch' && (inputs.job_to_run == 'all' || inputs.job_to_run == 'test'))
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create Files from Secrets
        env:
          A_LIST: ${{ secrets.A_LIST }}
          A_REQ: ${{ secrets.A_REQ }}
          A_TEST: ${{ secrets.A_TEST }}
        run: |
          echo "$A_LIST" > a.txt
          echo "$A_REQ" > req.txt
          echo "$A_TEST" > test.py

      - name: Install Dependencies
        run: |
          if [ -f req.txt ]; then pip install -r req.txt; fi

      - name: Run
        run: |
          python test.py > /dev/null 2>&1

      - name: Commit and Push State
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f data ]; then
            git pull
            git add data
            git commit -m "Update" || echo "No changes to commit"
            git push
          fi

  test_c:
    if: github.event.schedule == '*/30 * * * *' || (github.event_name == 'workflow_dispatch' && (inputs.job_to_run == 'all' || inputs.job_to_run == 'test_c'))
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create Files from Secrets
        env:
          R_LIST: ${{ secrets.R_LIST }}
          R_REQ: ${{ secrets.R_REQ }}
          R_TEST: ${{ secrets.R_TEST }}
        run: |
          echo "$R_LIST" > a.txt
          echo "$R_REQ" > req.txt
          echo "$R_TEST" > test.py

      - name: Install Dependencies
        run: |
          if [ -f req.txt ]; then pip install -r req.txt; fi

      - name: Run
        run: |
          python test.py

      - name: Commit and Push State
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f data3 ]; then
            git pull
            git add data3
            git commit -m "Update" || echo "No changes to commit"
            git push
          fi
